/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __c_c_file__
#define __c_c_file__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jint JNICALL Java_c_1c_1file_c_1open (JNIEnv *env, jobject, jstring);
JNIEXPORT void JNICALL Java_c_1c_1file_c_1fcntl (JNIEnv *env, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_c_1c_1file_c_1write (JNIEnv *env, jobject, jint, jstring, jint);
JNIEXPORT jstring JNICALL Java_c_1c_1file_c_1read (JNIEnv *env, jobject, jint);
JNIEXPORT jint JNICALL Java_c_1c_1file_c_1n_1read (JNIEnv *env, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __c_c_file__ */
