#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.1 on Fri Feb 22 22:37:32 2008

import wx
import serial, reprap, time, sys



# begin wxGlade: extracode
# end wxGlade

def printPos():
	x, y, z = reprap.cartesian.getPos()
	print "Location [" + str(x) + ", " + str(y) + ", " + str(z) + "]"


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_2 = wx.StaticText(self, -1, "Comms")
        self.btnInit = wx.Button(self, -1, "Init")
        self.label_1 = wx.StaticText(self, -1, "Cartesian : ")
        self.btnHome = wx.Button(self, -1, "Home Reset")
        self.btnStop = wx.Button(self, -1, "Stop")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.hanInit, self.btnInit)
        self.Bind(wx.EVT_BUTTON, self.hanHomeReset, self.btnHome)
        self.Bind(wx.EVT_BUTTON, self.hanStop, self.btnStop)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_2_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_5.Add(self.label_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_5.Add(self.btnInit, 0, wx.ADJUST_MINSIZE, 0)
        sizer_4.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_2_copy.Add(self.label_1, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        sizer_2_copy.Add(self.btnHome, 0, wx.ADJUST_MINSIZE, 0)
        sizer_2_copy.Add(self.btnStop, 0, wx.ADJUST_MINSIZE, 0)
        sizer_4.Add(sizer_2_copy, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_3.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

    def hanHomeReset(self, event): # wxGlade: MyFrame.<event_handler>
	reprap.cartesian.homeReset( 200, True )
	printPos()
        event.Skip()

    def hanStop(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `hanStop' not implemented!"
        event.Skip()

    def hanInit(self, event): # wxGlade: MyFrame.<event_handler>
        reprap.serial = serial.Serial(0, 19200, timeout = 60)

	reprap.cartesian.x.active = True	# these devices are present in network
	reprap.cartesian.y.active = True
	reprap.cartesian.z.active = True
	reprap.extruder.active = True

	#reprap.cartesian.x.setNotify()						
	#reprap.cartesian.y.setNotify()
	#reprap.cartesian.z.setNotify()
	reprap.cartesian.x.limit = 2523
	reprap.cartesian.y.limit = 2743
        event.Skip()

# end of class MyFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frmMain = MyFrame(None, -1, "")
    app.SetTopWindow(frmMain)
    frmMain.Show()
    app.MainLoop()
