#!/bin/bash

#convert our comms board outputs to pdf
echo "Converting PowerComms board to pdf."
ps2pdf Comms_and_power_distribution/comms_and_power_distribution-Copper.ps Comms_and_power_distribution/comms_and_power_distribution-Copper.pdf
ps2pdf Comms_and_power_distribution/comms_and_power_distribution-SilkSCmp.ps Comms_and_power_distribution/comms_and_power_distribution-SilkSCmp.pdf

#convert our universal controller to pdf
echo "Converting Universal Controller board to pdf."
ps2pdf Universal-pcb/stepper-and-extruder-Component.ps  Universal-pcb/stepper-and-extruder-Component.pdf
ps2pdf Universal-pcb/stepper-and-extruder-Copper.ps  Universal-pcb/stepper-and-extruder-Copper.pdf
ps2pdf Universal-pcb/stepper-and-extruder-SilkSCmp.ps  Universal-pcb/stepper-and-extruder-SilkSCmp.pdf

echo "Done."
