/* Generated By:JavaCC: Do not edit this line. MetaCADParserTreeConstants.java Version 4.2 */
package org.reprap.artofillusion.metacad.parser;

public interface MetaCADParserTreeConstants
{
  public int JJTPARSEDTREE = 0;
  public int JJTPARSEDTREELIST = 1;
  public int JJTFUNCTIONCALLLIST = 2;
  public int JJTFUNCTIONCALL = 3;
  public int JJTPARAMETERLIST = 4;
  public int JJTJEPFUNCTIONCALL = 5;
  public int JJTUNARYEXPRESSION = 6;
  public int JJTEXPRESSION = 7;
  public int JJTVARIABLEASSIGNMENT = 8;
  public int JJTMACROPROTOTYPE = 9;
  public int JJTPARSEDSTATEMENTLIST = 10;


  public String[] jjtNodeName = {
    "ParsedTree",
    "ParsedTreeList",
    "FunctionCallList",
    "FunctionCall",
    "ParameterList",
    "JEPFunctionCall",
    "UnaryExpression",
    "Expression",
    "VariableAssignment",
    "MacroPrototype",
    "ParsedStatementList",
  };
}
/* JavaCC - OriginalChecksum=5fb6a3409133ba7ae09e90a0356ba12c (do not edit this line) */
