#!/bin/bash

#init up
BOARD=`basename $1`
VERSION=${2:-`date +%Y-%m-%d`}
TO_DIR="reprap-$BOARD-$VERSION"
FILELIST=""

#directory structure
echo "Making Files..."
mkdir -p "$TO_DIR"
mkdir -p "$TO_DIR/gerber"
mkdir -p "$TO_DIR/eagle"

#copy our files...
echo "Copying Files..."
cp $BOARD/*.cmp "$TO_DIR/gerber/ComponentTraces.pho"
cp $BOARD/*.sol "$TO_DIR/gerber/CopperTraces.pho"
cp $BOARD/*.stc "$TO_DIR/gerber/SolderMaskComponent.pho"
cp $BOARD/*.sts "$TO_DIR/gerber/SolderMaskCopper.pho"
cp $BOARD/*.plc "$TO_DIR/gerber/SilkScreen.pho"
cp $BOARD/*.drl "$TO_DIR/gerber"
cp $BOARD/*.drd "$TO_DIR/gerber"

#create our source dir
cp $BOARD/*.brd "$TO_DIR/eagle/";
cp $BOARD/*.sch "$TO_DIR/eagle/";
cp $BOARD/*.pro "$TO_DIR/eagle/";

#convert to pdf...
#echo "Converting to PDF..."
#for PS in $TO_DIR/pdf/*.ps
#do
#	TO_FILE=`basename $PS .ps`.pdf
#	ps2pdf $PS $TO_DIR/pdf/$TO_FILE
#done
#rm $TO_DIR/pdf/*.ps

#create our archive
echo "Archiving..."
zip -qr "$TO_DIR.zip" "$TO_DIR"

#cleanup
echo "Cleanup..."
rm -rf "$TO_DIR"

#done!
echo "Release v$VERSION created as ${TO_DIR}.zip"
