#!/bin/bash

#convert our power / comms to pdf
echo "Converting PowerComms board to pdf."
ps2pdf PowerComms/comms_and_power_distribution-Copper.ps  PowerComms/comms_and_power_distribution-Copper.pdf
ps2pdf PowerComms/comms_and_power_distribution-SilkSCmp.ps  PowerComms/comms_and_power_distribution-SilkSCmp.pdf

#convert our universal controller to pdf
echo "Converting Universal Controller board to pdf."
ps2pdf UniversalController/universal-Component.ps  UniversalController/universal-Component.pdf
ps2pdf UniversalController/universal-Copper.ps  UniversalController/universal-Copper.pdf
ps2pdf UniversalController/universal-SilkSCmp.ps  UniversalController/universal-SilkSCmp.pdf

echo "Done."
