#!/bin/bash

#init up
VERSION=$1
TO_DIR="reprap-firmware-$VERSION"

#directory structure
mkdir -p "$TO_DIR"

#make the firmware nice
cp build/16f628/extruder/extruder.hex "$TO_DIR/" 2>/dev/null
cp build/16f628/iobox/iobox.hex "$TO_DIR/" 2>/dev/null
cp build/16f628/stepmotor/stepmotor.hex "$TO_DIR/" 2>/dev/null
cp build/16f628/stepmotorb/stepmotorb.hex "$TO_DIR/" 2>/dev/null
cp build/16f628/stepmotorc/stepmotorc.hex "$TO_DIR/" 2>/dev/null
cp build/16f628/stepmotor-small/stepmotor-small.hex "$TO_DIR/" 2>/dev/null

#create our archive
zip -qr "$TO_DIR.zip" "$TO_DIR"

#cleanup
rm -rf "$TO_DIR"

echo "RepRap Firmware Release v$VERSION created."
